### ISSUE TITLE
Britney crashes in _compute_groups when attempting migration

### ISSUE THREAD

**Issue by ximion** [Debian/britney2#24]
Hi!
This is a slightly different form of the issue we recently discussed on IRC, but it likely has the same cause: arch:all package being available in different versions in arm64 vs amd64 for some reason.

Britney crashes with the following error:
```
I: [2018-06-06T19:54:54+0000] -   most: (92) .. kicad-templates kimagemapeditor -python-msrestazure kicad-footprints kicad-packages3d kopano-webapp libgitlab-api-v4-perl cross-toolchain-base-ports emacs-jabber pxz fonts-sawarabi-gothic ruby-sidekiq-limit-fetch golang-github-go-ini-ini apache-directory-server python-certbot-dns-digitalocean stenographer t4kcommon libsdl1.2 emacs-ctable refpolicy
I: [2018-06-06T19:54:54+0000] - trying: r-cran-bayesplot
I: [2018-06-06T19:54:54+0000] - skipped: r-cran-bayesplot (41, 0, 10)
I: [2018-06-06T19:54:54+0000] -     got: 17398+0: a-14680:a-2718
I: [2018-06-06T19:54:54+0000] -     * amd64: r-cran-bayesplot
I: [2018-06-06T19:54:54+0000] - trying: neutron
I: [2018-06-06T19:54:54+0000] - skipped: neutron (41, 1, 9)
I: [2018-06-06T19:54:54+0000] -     got: 17398+0: a-14680:a-2718
I: [2018-06-06T19:54:54+0000] -     * amd64: neutron-plugin-openvswitch-agent
I: [2018-06-06T19:54:54+0000] - trying: selinux-dbus selinux-python

Traceback (most recent call last):
  File "/srv/laniakea/dist/britney2/britney.py", line 2857, in <module>
    Britney().main()
  File "/srv/laniakea/dist/britney2/britney.py", line 2846, in main
    self.upgrade_testing()
  File "/srv/laniakea/dist/britney2/britney.py", line 2493, in upgrade_testing
    self.do_all()
  File "/srv/laniakea/dist/britney2/britney.py", line 2359, in do_all
    (nuninst_end, extra) = self.iter_packages(upgrade_me, selected, nuninst=nuninst_end, lundo=lundo)
  File "/srv/laniakea/dist/britney2/britney.py", line 2250, in iter_packages
    accepted, nuninst_after, comp_undo, failed_arch = self.try_migration(comp, nuninst_last_accepted, lundo)
  File "/srv/laniakea/dist/britney2/britney.py", line 2149, in try_migration
    allow_smooth_updates=False)
  File "/srv/laniakea/dist/britney2/britney.py", line 1855, in _compute_groups
    if binaries_t[parch][0][binary].source != source_name:
KeyError: 'policycoreutils-gui'
```

Given this configuration file (slightly reduced and simplified here):
```
NONINST_STATUS      = output/target/non-installable-status
EXCUSES_OUTPUT      = output/target/excuses.html
EXCUSES_YAML_OUTPUT = output/target/excuses.yaml
UPGRADE_OUTPUT      = output/target/output.txt
HEIDI_OUTPUT        = output/target/HeidiResult
STATIC_INPUT_DIR = input/
HINTSDIR         = input/hints
STATE_DIR        = state/
HINTS_LANIAKEA   = ALL
SMOOTH_UPDATES = libs oldlibs
IGNORE_CRUFT   = 1
UNSTABLE = /path/to/landing
TESTING  = /path/to/purple
COMPONENTS = main
ARCHITECTURES = amd64 arm64
NOBREAKALL_ARCHES = amd64
MINDAYS_LOW = 0
MINDAYS_EMERGENCY = 0
MINDAYS_CRITICAL = 0
MINDAYS_HIGH = 0
MINDAYS_MEDIUM = 0
DEFAULT_URGENCY   = medium
OUTOFSYNC_ARCHES  = amd64 arm64
BREAK_ARCHES      =
NEW_ARCHES        =
```

And using these Packages/Sources as input: https://people.debian.org/~mak/share/pureos-mindist-britney-crash.zip (file is a bit bigger than what could be uploaded here).

Britney2 is at commit `d11152b36601bf81c2ab0f24a476654bb1e59eff` when showing this crash.
A difference to the previous crash (at the same position) that did show up first is that this time, arm64 is not in BREAK_ARCHES.

If there is any further information you need or anything I can help with, please let me know!
Thank you!

**Comment by ximion** [comment]
This issue has been moved to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=901248
